name: Internship Scraper

on:
  schedule:
    - cron: "*/5 * * * *" # Every 10 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          MY_TELEGRAM_ID: ${{ secrets.MY_TELEGRAM_ID }}
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
        run: python intern.py

      - name: Update company.txt
        run: |
          git config user.name "Duong Hai Lam"
          git config user.email "Hailam2104@users.noreply.github.com"
          if git status --porcelain | grep .; then
            git add .
            git commit -m "Update company.txt, numbers.txt, ids.txt"
            git push
          else
            echo "No changes to commit."
          fi
